{:schema_name "sys" :table_name "ot_usergroups" :field_name "value" :type "text" :is_function false :is_id true :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Value" :control "text" :location 0 :in_table_view true :disabled false :readonly false :required false :size 25 :text_max_length 25 :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "ot_usergroups" :field_name "label" :type "text" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Label" :control "text" :location 1 :in_table_view true :disabled false :readonly false :required true :size 25 :text_max_length 25 :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "ot_usergroups" :field_name "location" :type "int8" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Location" :control "integer" :location 2 :in_table_view true :disabled false :readonly false :required true :size 6 :text_max_length nil :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step 1 :integer_min 0 :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}



{:schema_name "sys" :table_name "users" :field_name "username" :type "text" :is_function false :is_id true :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Username" :control "text" :location 0 :in_table_view true :disabled false :readonly false :required false :size 25 :text_max_length 25 :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "users" :field_name "password" :type "text" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Password" :control "text" :location 1 :in_table_view false :disabled false :readonly false :required true :size 25 :text_max_length 25 :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "users" :field_name "full_name" :type "text" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Full Name" :control "text" :location 2 :in_table_view true :disabled false :readonly false :required true :size 50 :text_max_length 50 :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "users" :field_name "display_name" :type "text" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Display Name" :control "text" :location 3 :in_table_view true :disabled false :readonly false :required true :size 25 :text_max_length 25 :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "users" :field_name "email" :type "text" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Email" :control "text" :location 4 :in_table_view true :disabled false :readonly false :required true :size 50 :text_max_length 50 :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "users" :field_name "usergroup" :type "text" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Usergroup" :control "select-option" :location 5 :in_table_view true :disabled false :readonly false :required true :size nil :text_max_length nil :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple false :select_size 1 :select_option_table "sys.ot_usergroups" :select_result_view nil :created_by "root" :updated_by "root"}



{:schema_name "sys" :table_name "ot_controls" :field_name "value" :type "text" :is_function false :is_id true :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Value" :control "text" :location 0 :in_table_view true :disabled false :readonly false :required false :size 25 :text_max_length 25 :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "ot_controls" :field_name "label" :type "text" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Label" :control "text" :location 1 :in_table_view true :disabled false :readonly false :required true :size 25 :text_max_length 25 :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "ot_controls" :field_name "location" :type "int8" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Location" :control "integer" :location 2 :in_table_view true :disabled false :readonly false :required true :size 6 :text_max_length nil :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step 1 :integer_min 0 :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}



{:schema_name "sys" :table_name "ot_types" :field_name "value" :type "text" :is_function false :is_id true :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Value" :control "text" :location 0 :in_table_view true :disabled false :readonly false :required false :size 25 :text_max_length 25 :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "ot_types" :field_name "label" :type "text" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Label" :control "text" :location 1 :in_table_view true :disabled false :readonly false :required true :size 25 :text_max_length 25 :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "ot_types" :field_name "location" :type "int8" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Location" :control "integer" :location 2 :in_table_view true :disabled false :readonly false :required true :size 6 :text_max_length nil :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step 1 :integer_min 0 :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}



{:schema_name "sys" :table_name "tables" :field_name "tables_id" :type "text" :is_function true :is_id true :is_uk false :is_fk false :is_settable false :search_fields_id nil :label "Tables ID" :control "text" :location 0 :in_table_view true :disabled true :readonly true :required false :size 25 :text_max_length 25 :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "tables" :field_name "schema_name" :type "text" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Schema Name" :control "text" :location 1 :in_table_view true :disabled false :readonly false :required true :size 6 :text_max_length 25 :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "tables" :field_name "table_name" :type "text" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Table Name" :control "text" :location 2 :in_table_view true :disabled false :readonly false :required true :size 25 :text_max_length 25 :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "tables" :field_name "table_type" :type "text" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Table Type" :control "select-option" :location 3 :in_table_view true :disabled false :readonly false :required true :size nil :text_max_length nil :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple false :select_size 1 :select_option_table "sys.ot_table_types" :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "tables" :field_name "is_table" :type "boolean" :is_function false :is_id false :is_uk false :is_fk false :is_settable false :search_fields_id nil :label "Is Table?" :control "select-boolean" :location 4 :in_table_view true :disabled true :readonly true :required false :size nil :text_max_length nil :textarea_cols nil :textarea_rows nil :boolean_true "Yes" :boolean_false "No" :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}


{:schema_name "sys" :table_name "tables" :field_name "is_view" :type "boolean" :is_function false :is_id false :is_uk false :is_fk false :is_settable false :search_fields_id nil :label "Is View?" :control "select-boolean" :location 5 :in_table_view true :disabled true :readonly true :required false :size nil :text_max_length nil :textarea_cols nil :textarea_rows nil :boolean_true "Yes" :boolean_false "No" :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "tables" :field_name "views_id" :type "text" :is_function true :is_id false :is_uk false :is_fk false :is_settable false :search_fields_id nil :label "VIews ID" :control "text" :location 6 :in_table_view false :disabled true :readonly true :required false :size 25 :text_max_length 25 :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "tables" :field_name "is_result_view" :type "boolean" :is_function false :is_id false :is_uk false :is_fk false :is_settable false :search_fields_id nil :label "Is Result View?" :control "select-boolean" :location 7 :in_table_view true :disabled true :readonly true :required false :size nil :text_max_length nil :textarea_cols nil :textarea_rows nil :boolean_true "Yes" :boolean_false "No" :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "tables" :field_name "result_views_id" :type "text" :is_function true :is_id false :is_uk false :is_fk false :is_settable false :search_fields_id nil :label "Result Views ID" :control "text" :location 8 :in_table_view false :disabled true :readonly true :required false :size 25 :text_max_length 25 :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "tables" :field_name "is_option_table" :type "boolean" :is_function false :is_id false :is_uk false :is_fk false :is_settable false :search_fields_id nil :label "Is Option Table?" :control "select-boolean" :location 9 :in_table_view true :disabled true :readonly true :required false :size nil :text_max_length nil :textarea_cols nil :textarea_rows nil :boolean_true "Yes" :boolean_false "No" :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "tables" :field_name "option_tables_id" :type "text" :is_function true :is_id false :is_uk false :is_fk false :is_settable false :search_fields_id nil :label "Option Tables ID" :control "text" :location 10 :in_table_view false :disabled true :readonly true :required false :size 25 :text_max_length 25 :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}



{:schema_name "sys" :table_name "fields" :field_name "fields_id" :type "text" :is_function false :is_id true :is_uk false :is_fk false :is_settable false :search_fields_id nil :label "Fields ID" :control "text" :location 0 :in_table_view true :disabled true :readonly true :required false :size 50 :text_max_length 80 :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "tables_id" :type "text" :is_function false :is_id false :is_uk false :is_fk true :is_settable false :search_fields_id "sys.tables.tables_id" :label "Tables ID" :control "text" :location 1 :in_table_view true :disabled true :readonly true :required false :size 25 :text_max_length 80 :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "schema_name" :type "text" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Schema Name" :control "text" :location 2 :in_table_view false :disabled false :readonly false :required true :size 6 :text_max_length 25 :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "table_name" :type "text" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Table Name" :control "text" :location 3 :in_table_view false :disabled false :readonly false :required true :size 25 :text_max_length 25 :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "field_name" :type "text" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Field Name" :control "text" :location 4 :in_table_view false :disabled false :readonly false :required true :size 25 :text_max_length 25 :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "type" :type "text" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Type" :control "select-option" :location 5 :in_table_view true :disabled false :readonly false :required true :size nil :text_max_length nil :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple false :select_size 1 :select_option_table "sys.ot_types" :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "is_function" :type "boolean" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Is Function?" :control "select-boolean" :location 6 :in_table_view true :disabled false :readonly false :required true :size nil :text_max_length nil :textarea_cols nil :textarea_rows nil :boolean_true "Yes" :boolean_false "No" :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "is_id" :type "boolean" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Is Id?" :control "select-boolean" :location 7 :in_table_view true :disabled false :readonly false :required true :size nil :text_max_length nil :textarea_cols nil :textarea_rows nil :boolean_true "Yes" :boolean_false "No" :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "is_uk" :type "boolean" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Is Unique Key?" :control "select-boolean" :location 8 :in_table_view true :disabled false :readonly false :required true :size nil :text_max_length nil :textarea_cols nil :textarea_rows nil :boolean_true "Yes" :boolean_false "No" :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "is_fk" :type "boolean" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Is Foreign Key?" :control "select-boolean" :location 9 :in_table_view true :disabled false :readonly false :required true :size nil :text_max_length nil :textarea_cols nil :textarea_rows nil :boolean_true "Yes" :boolean_false "No" :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "is_settable" :type "boolean" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Is Settable?" :control "select-boolean" :location 10 :in_table_view true :disabled false :readonly false :required true :size nil :text_max_length nil :textarea_cols nil :textarea_rows nil :boolean_true "Yes" :boolean_false "No" :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "label" :type "text" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Label" :control "text" :location 11 :in_table_view true :disabled false :readonly false :required true :size 25 :text_max_length 25 :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "control" :type "text" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Control" :control "select-option" :location 12 :in_table_view true :disabled false :readonly false :required true :size nil :text_max_length nil :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple false :select_size 1 :select_option_table "sys.ot_controls" :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "size" :type "int8" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Size" :control "integer" :location 13 :in_table_view true :disabled false :readonly false :required true :size 6 :text_max_length nil :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step 1 :integer_min 0 :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "disabled" :type "boolean" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Disabled?" :control "select-boolean" :location 14 :in_table_view true :disabled false :readonly false :required true :size nil :text_max_length nil :textarea_cols nil :textarea_rows nil :boolean_true "Yes" :boolean_false "No" :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "readonly" :type "boolean" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Readonly?" :control "select-boolean" :location 15 :in_table_view true :disabled false :readonly false :required true :size nil :text_max_length nil :textarea_cols nil :textarea_rows nil :boolean_true "Yes" :boolean_false "No" :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "required" :type "boolean" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Required?" :control "select-boolean" :location 16 :in_table_view true :disabled false :readonly false :required true :size nil :text_max_length nil :textarea_cols nil :textarea_rows nil :boolean_true "Yes" :boolean_false "No" :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "location" :type "int8" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Location" :control "integer" :location 17 :in_table_view true :disabled false :readonly false :required true :size 6 :text_max_length nil :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step 1 :integer_min 0 :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "in_table_view" :type "boolean" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "In Table View?" :control "select-boolean" :location 18 :in_table_view false :disabled false :readonly false :required true :size nil :text_max_length nil :textarea_cols nil :textarea_rows nil :boolean_true "Yes" :boolean_false "No" :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "search_fields_id" :type "text" :is_function false :is_id false :is_uk false :is_fk true :is_settable true :search_fields_id "sys.fields.fields_id" :label "Search Fields ID" :control "select-result" :location 19 :in_table_view false :disabled false :readonly false :required false :size nil :text_max_length nil :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple false :select_size 10 :select_option_table nil :select_result_view "sys.rv_fields" :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "boolean_true" :type "text" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Boolean True" :control "text" :location 20 :in_table_view false :disabled false :readonly false :required false :size 25 :text_max_length 25 :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "boolean_false" :type "text" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Boolean False" :control "text" :location 21 :in_table_view false :disabled false :readonly false :required false :size 25 :text_max_length 25 :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "date_min" :type "date" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Date Min" :control "date" :location 22 :in_table_view false :disabled false :readonly false :required false :size 10 :text_max_length nil :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "date_max" :type "date" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Date Max" :control "date" :location 23 :in_table_view false :disabled false :readonly false :required false :size 10 :text_max_length nil :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "integer_step" :type "int8" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Integer Step" :control "integer" :location 24 :in_table_view false :disabled false :readonly false :required false :size 6 :text_max_length nil :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step 1 :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "integer_min" :type "int8" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Integer Min" :control "integer" :location 25 :in_table_view false :disabled false :readonly false :required false :size 6 :text_max_length nil :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step 1 :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "integer_max" :type "int8" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Integer Max" :control "integer" :location 26 :in_table_view false :disabled false :readonly false :required false :size 6 :text_max_length nil :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step 1 :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "float_step" :type "float8" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Float Step" :control "float" :location 27 :in_table_view false :disabled false :readonly false :required false :size 6 :text_max_length nil :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step 1.0E-10 :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "float_min" :type "float8" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Float Min" :control "float" :location 28 :in_table_view false :disabled false :readonly false :required false :size 6 :text_max_length nil :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step 1.0E-10 :float_min -1.0E-307 :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "float_max" :type "float8" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Float Max" :control "float" :location 29 :in_table_view false :disabled false :readonly false :required false :size 6 :text_max_length nil :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step 1.0E-10 :float_min nil :float_max 1.0E308 :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "select_multiple" :type "boolean" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Select Multiple?" :control "select-boolean" :location 30 :in_table_view false :disabled false :readonly false :required false :size nil :text_max_length nil :textarea_cols nil :textarea_rows nil :boolean_true "Yes" :boolean_false "No" :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "select_size" :type "int8" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Select Size" :control "integer" :location 31 :in_table_view false :disabled false :readonly false :required false :size 6 :text_max_length nil :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step 1 :integer_min 0 :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "select_option_table" :type "text" :is_function false :is_id false :is_uk false :is_fk true :is_settable true :search_fields_id "sys.fields.fields_id" :label "Select Option Table" :control "select-result" :location 32 :in_table_view false :disabled false :readonly false :required false :size nil :text_max_length nil :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple false :select_size 5 :select_option_table nil :select_result_view "sys.rv_option_tables" :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "select_result_view" :type "text" :is_function false :is_id false :is_uk false :is_fk true :is_settable true :search_fields_id "sys.fields.fields_id" :label "Select Result View" :control "select-result" :location 33 :in_table_view false :disabled false :readonly false :required false :size nil :text_max_length nil :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple false :select_size 5 :select_option_table nil :select_result_view"sys.rv_result_views" :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "text_max_length" :type "int8" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Text Max Length" :control "integer" :location 34 :in_table_view false :disabled false :readonly false :required false :size 6 :text_max_length nil :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step 1 :integer_min 1 :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "textarea_cols" :type "int8" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Text Area Columns" :control "integer" :location 35 :in_table_view false :disabled false :readonly false :required false :size 6 :text_max_length nil :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step 1 :integer_min 0 :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "textarea_rows" :type "int8" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Text Area Rows" :control "integer" :location 36 :in_table_view false :disabled false :readonly false :required false :size 6 :text_max_length nil :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step 1 :integer_min 0 :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}



{:schema_name "sys" :table_name "event_classes" :field_name "event_classes_id" :type "text" :is_function false :is_id true :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Event Classes ID" :control "select-result" :location 0 :in_table_view true :disabled false :readonly false :required false :size nil :text_max_length nil :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple false :select_size 10 :select_option_table nil :select_result_view "sys.rv_event_classes" :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "event_classes" :field_name "function_name" :type "text" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Function name" :control "select-result" :location 1 :in_table_view true :disabled false :readonly false :required true :size nil :text_max_length nil :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple false :select_size 10 :select_option_table nil :select_result_view "sys.rv_function_names" :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "event_classes" :field_name "argument_name_id" :type "text" :is_function false :is_id false :is_uk false :is_fk true :is_settable true :search_fields_id "sys.fields.fields_id" :label "Argument Name ID" :control "select-result" :location 2 :in_table_view true :disabled false :readonly false :required false :size nil :text_max_length nil :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple false :select_size 10 :select_option_table nil :select_result_view "sys.rv_fields" :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "event_classes" :field_name "precedence_expression" :type "text" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Precedence Expression" :control "text" :location 3 :in_table_view true :disabled false :readonly false :required true :size 25 :text_max_length 25 :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}



{:schema_name "sys" :table_name "event_class_fields" :field_name "event_class_fields_id" :type "text" :is_function false :is_id true :is_uk false :is_fk false :is_settable false :search_fields_id nil :label "Event Class Fields ID" :control "text" :location 0 :in_table_view true :disabled true :readonly true :required false :size 50 :text_max_length 80 :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "event_class_fields" :field_name "event_classes_id" :type "text" :is_function false :is_id false :is_uk false :is_fk true :is_settable true :search_fields_id nil :label "Event Classes ID" :control "select-result" :location 1 :in_table_view true :disabled false :readonly false :required true :size nil :text_max_length nil :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple false :select_size 10 :select_option_table nil :select_result_view "sys.rv_event_classes"  :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "event_class_fields" :field_name "field_name" :type "text" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Field Name" :control "text" :location 2 :in_table_view true :disabled false :readonly false :required true :size 25 :text_max_length 25 :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "event_class_fields" :field_name "sys_fields_id" :type "text" :is_function false :is_id false :is_uk false :is_fk true :is_settable true :search_fields_id "sys.fields.fields_id" :label "Fields ID" :control "select-result" :location 3 :in_table_view true :disabled false :readonly false :required true :size nil :text_max_length nil :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple false :select_size 10 :select_option_table nil :select_result_view "sys.rv_fields" :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "event_class_fields" :field_name "label" :type "text" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Label" :control "text" :location 4 :in_table_view false :disabled false :readonly false :required true :size 25 :text_max_length 25 :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "event_class_fields" :field_name "location" :type "int8" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Location" :control "integer" :location 5 :in_table_view true :disabled false :readonly false :required true :size 6 :text_max_length nil :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step 1 :integer_min 0 :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}




{:schema_name "sys" :table_name "field_sets" :field_name "field_sets_id" :type "text" :is_function false :is_id true :is_uk false :is_fk false :is_settable false :search_fields_id nil :label "Field Sets ID" :control "text" :location 0 :in_table_view true :disabled true :readonly true :required false :size 50 :text_max_length 80 :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "field_sets" :field_name "tables_id" :type "text" :is_function false :is_id false :is_uk false :is_fk false :is_settable false :search_fields_id nil :label "Tables ID" :control "text" :location 1 :in_table_view true :disabled true :readonly true :required false :size 25 :text_max_length 25 :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "field_sets" :field_name "schema_name" :type "text" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Schema Name" :control "text" :location 2 :in_table_view true :disabled false :readonly false :required true :size 6 :text_max_length 25 :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "field_sets" :field_name "table_name" :type "text" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Table Name" :control "text" :location 3 :in_table_view true :disabled false :readonly false :required true :size 25 :text_max_length 25 :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "field_sets" :field_name "field_name" :type "text" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Field Name" :control "text" :location 4 :in_table_view true :disabled false :readonly false :required true :size 25 :text_max_length 25 :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "field_sets" :field_name "sys_fields_id" :type "text" :is_function false :is_id false :is_uk false :is_fk true :is_settable true :search_fields_id "sys.fields.fields_id" :label "Sys Fields ID" :control "select-result" :location 5 :in_table_view false :disabled false :readonly false :required true :size nil :text_max_length nil :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple false :select_size 10 :select_option_table nil :select_result_view "sys.rv_fields" :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "field_sets" :field_name "label" :type "text" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Label" :control "text" :location 8 :in_table_view false :disabled false :readonly false :required true :size 25 :text_max_length 25 :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "field_sets" :field_name "location" :type "int8" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Location" :control "integer" :location 9 :in_table_view false :disabled false :readonly false :required true :size 6 :text_max_length nil :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step 1 :integer_min 0 :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}



{:schema_name "sys" :table_name "events" :field_name "events_id" :type "serial8" :is_function false :is_id true :is_uk false :is_fk false :is_settable false :search_fields_id nil :label "ID" :control "integer" :location 0 :in_table_view true :disabled true :readonly true :required false :size 6 :text_max_length nil :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "events" :field_name "event_classes_id" :type "text" :is_function false :is_id false :is_uk false :is_fk true :is_settable true :search_fields_id nil :label "Event Classes ID" :control "select-result" :location 1 :in_table_view true :disabled false :readonly false :required true :size nil :text_max_length nil :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple false :select_size 10 :select_option_table nil :select_result_view "sys.rv_event_classes" :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "events" :field_name "event_by" :type "text" :is_function false :is_id false :is_uk false :is_fk true :is_settable true :search_fields_id nil :label "Event By" :control "select-result" :location 2 :in_table_view true :disabled false :readonly false :required true :size nil :text_max_length nil :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple false :select_size 10 :select_option_table nil :select_result_view "sys.rv_users" :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "events" :field_name "event_at" :type "date" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Event At" :control "date" :location 3 :in_table_view true :disabled false :readonly false :required true :size 10 :text_max_length nil :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "events" :field_name "event_data" :type "jsonb" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Data" :control "textarea" :location 4 :in_table_view false :disabled false :readonly false :required true :size nil :text_max_length 2048 :textarea_cols 80 :textarea_rows 10 :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "events" :field_name "event_notes" :type "text" :is_function false :is_id false :is_uk false :is_fk false :is_settable true :search_fields_id nil :label "Notes" :control "textarea" :location 5 :in_table_view false :disabled false :readonly false :required false :size nil :text_max_length 2048 :textarea_cols 80 :textarea_rows 10 :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}



{:schema_name "sys" :table_name "event_queue" :field_name "event_queue_id" :type "serial8" :is_function false :is_id true :is_uk false :is_fk false :is_settable false :search_fields_id nil :label "ID" :control "integer" :location 0 :in_table_view true :disabled true :readonly true :required false :size 6 :text_max_length nil :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :select_option_table nil :select_result_view nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "event_queue" :field_name "event_classes_id" :type "text" :is_function false :is_id false :is_uk false :is_fk true :is_settable true :search_fields_id "sys.event_classes.event_classes_id" :label "Event Classes ID" :control "select-result" :location 1 :in_table_view true :disabled false :readonly false :required false :size nil :text_max_length nil :textarea_cols nil :textarea_rows nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :datetime_min nil :datetime_max nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple false :select_size 10 :select_option_table nil :select_result_view "sys.rv_event_classes" :created_by "root" :updated_by "root"}


