{:fields_id "sys.fields.fields_id" :type "text" :is_pk true :is_pk_in_new true :label "Fields ID" :control "text-key" :location 0 :in_table_view true :disabled false :readonly true :required false :text_max_length 80 :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:fields_id "sys.fields.schema_name" :type "text" :is_pk false :is_pk_in_new nil :label "Schema Name" :control "text" :location 1 :in_table_view true :disabled false :readonly false :required true :text_max_length 25 :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:fields_id "sys.fields.table_name" :type "text" :is_pk false :is_pk_in_new nil :label "Table Name" :control "text" :location 2 :in_table_view true :disabled false :readonly false :required true :text_max_length 25 :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:fields_id "sys.fields.field_name" :type "text" :is_pk false :is_pk_in_new nil :label "Field Name" :control "text" :location 3 :in_table_view true :disabled false :readonly false :required true :text_max_length 25 :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:fields_id "sys.fields.type" :type "text" :is_pk false :is_pk_in_new nil :label "Type" :control "select" :location 4 :in_table_view true :disabled false :readonly false :required true :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple false :select_size 1 :options_schema_table "sys.options_types" :created_by "root" :updated_by "root"}

{:fields_id "sys.fields.is_pk" :type "boolean" :is_pk false :is_pk_in_new nil :label "Is Primary Key?" :control "boolean-select" :location 5 :in_table_view false :disabled false :readonly false :required true :text_max_length nil :boolean_true "Yes" :boolean_false "No" :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:fields_id "sys.fields.is_pk_in_new" :type "boolean" :is_pk false :is_pk_in_new nil :label "Is Primary Key In New?" :control "boolean-select" :location 6 :in_table_view false :disabled false :readonly false :required true :text_max_length nil :boolean_true "Yes" :boolean_false "No" :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:fields_id "sys.fields.label" :type "text" :is_pk false :is_pk_in_new nil :label "Label" :control "text" :location 7 :in_table_view true :disabled false :readonly false :required true :text_max_length 25 :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:fields_id "sys.fields.control" :type "text" :is_pk false :is_pk_in_new nil :label "Control" :control "select" :location 8 :in_table_view true :disabled false :readonly false :required true :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple false :select_size 1 :options_schema_table "sys.options_controls" :created_by "root" :updated_by "root"}

{:fields_id "sys.fields.location" :type "int8" :is_pk false :is_pk_in_new nil :label "Location" :control "integer" :location 9 :in_table_view false :disabled false :readonly false :required true :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step 1 :integer_min 0 :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:fields_id "sys.fields.in_table_view" :type "boolean" :is_pk false :is_pk_in_new nil :label "In Table View?" :control "boolean-select" :location 10 :in_table_view false :disabled false :readonly false :required true :text_max_length nil :boolean_true "Yes" :boolean_false "No" :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:fields_id "sys.fields.boolean_true" :type "text" :is_pk false :is_pk_in_new nil :label "Boolean True" :control "text" :location 11 :in_table_view false :disabled false :readonly false :required false :text_max_length 25 :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:fields_id "sys.fields.boolean_false" :type "text" :is_pk false :is_pk_in_new nil :label "Boolean False" :control "text" :location 12 :in_table_view false :disabled false :readonly false :required false :text_max_length 25 :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:fields_id "sys.fields.date_min" :type "date" :is_pk false :is_pk_in_new nil :label "Date Min" :control "date" :location 13 :in_table_view false :disabled false :readonly false :required false :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:fields_id "sys.fields.date_max" :type "date" :is_pk false :is_pk_in_new nil :label "Date Max" :control "date" :location 14 :in_table_view false :disabled false :readonly false :required false :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:fields_id "sys.fields.integer_step" :type "int8" :is_pk false :is_pk_in_new nil :label "Integer Step" :control "integer" :location 15 :in_table_view false :disabled false :readonly false :required false :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step 1 :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:fields_id "sys.fields.integer_min" :type "int8" :is_pk false :is_pk_in_new nil :label "Integer Min" :control "integer" :location 16 :in_table_view false :disabled false :readonly false :required false :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step 1 :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:fields_id "sys.fields.integer_max" :type "int8" :is_pk false :is_pk_in_new nil :label "Integer Max" :control "integer" :location 17 :in_table_view false :disabled false :readonly false :required false :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step 1 :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:fields_id "sys.fields.float_step" :type "float8" :is_pk false :is_pk_in_new nil :label "Float Step" :control "float" :location 18 :in_table_view false :disabled false :readonly false :required false :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step 1.0E-10 :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:fields_id "sys.fields.float_min" :type "float8" :is_pk false :is_pk_in_new nil :label "Float Min" :control "float" :location 19 :in_table_view false :disabled false :readonly false :required false :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step 1.0E-10 :float_min -1.0E-307 :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:fields_id "sys.fields.float_max" :type "float8" :is_pk false :is_pk_in_new nil :label "Float Max" :control "float" :location 20 :in_table_view false :disabled false :readonly false :required false :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step 1.0E-10 :float_min nil :float_max 1.0E308 :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:fields_id "sys.fields.select_multiple" :type "boolean" :is_pk false :is_pk_in_new nil :label "Select Multiple?" :control "boolean-select" :location 21 :in_table_view false :disabled false :readonly false :required false :text_max_length nil :boolean_true "Yes" :boolean_false "No" :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:fields_id "sys.fields.select_size" :type "int8" :is_pk false :is_pk_in_new nil :label "Select Size" :control "integer" :location 22 :in_table_view false :disabled false :readonly false :required false :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step 1 :integer_min 0 :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:fields_id "sys.fields.options_schema_table" :type "text" :is_pk false :is_pk_in_new nil :label "Options Schema Table" :control "text" :location 23 :in_table_view false :disabled false :readonly false :required false :text_max_length 24 :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:fields_id "sys.fields.text_max_length" :type "int8" :is_pk false :is_pk_in_new nil :label "Text Max Length" :control "integer" :location 24 :in_table_view false :disabled false :readonly false :required false :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step 1 :integer_min 1 :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:fields_id "sys.fields.disabled" :type "boolean" :is_pk false :is_pk_in_new nil :label "Disabled?" :control "boolean-select" :location 25 :in_table_view false :disabled false :readonly false :required true :text_max_length nil :boolean_true "Yes" :boolean_false "No" :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:fields_id "sys.fields.readonly" :type "boolean" :is_pk false :is_pk_in_new nil :label "Readonly?" :control "boolean-select" :location 26 :in_table_view false :disabled false :readonly false :required true :text_max_length nil :boolean_true "Yes" :boolean_false "No" :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:fields_id "sys.fields.required" :type "boolean" :is_pk false :is_pk_in_new nil :label "Required?" :control "boolean-select" :location 27 :in_table_view false :disabled false :readonly false :required true :text_max_length nil :boolean_true "Yes" :boolean_false "No" :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:fields_id "sys.users.username" :type "text" :is_pk true :is_pk_in_new true :label "Username" :control "text-key" :location 0 :in_table_view true :disabled false :readonly true :required false :text_max_length 25 :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:fields_id "sys.users.password" :type "text" :is_pk false :is_pk_in_new nil :label "Password" :control "text" :location 2 :in_table_view true :disabled false :readonly false :required true :text_max_length 25 :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:fields_id "sys.users.usergroup" :type "text" :is_pk false :is_pk_in_new nil :label "Usergroup" :control "select" :location 3 :in_table_view true :disabled false :readonly false :required true :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple false :select_size 1 :options_schema_table "sys.options_usergroups" :created_by "root" :updated_by "root"}

{:fields_id "sys.options_controls.id" :type "serial8" :is_pk true :is_pk_in_new nil :label "ID" :control "integer-key" :location 0 :in_table_view true :disabled false :readonly true :required false :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:fields_id "sys.options_controls.label" :type "text" :is_pk false :is_pk_in_new nil :label "Label" :control "text" :location 1 :in_table_view true :disabled false :readonly false :required true :text_max_length 25 :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:fields_id "sys.options_controls.value" :type "text" :is_pk false :is_pk_in_new nil :label "Value" :control "text" :location 2 :in_table_view true :disabled false :readonly false :required true :text_max_length 25 :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:fields_id "sys.options_controls.location" :type "int8" :is_pk false :is_pk_in_new nil :label "Location" :control "integer" :location 8 :in_table_view true :disabled false :readonly false :required true :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step 1 :integer_min 0 :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:fields_id "sys.options_types.id" :type "serial8" :is_pk true :is_pk_in_new nil :label "ID" :control "integer-key" :location 0 :in_table_view true :disabled false :readonly true :required false :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:fields_id "sys.options_types.label" :type "text" :is_pk false :is_pk_in_new nil :label "Label" :control "text" :location 1 :in_table_view true :disabled false :readonly false :required true :text_max_length 25 :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:fields_id "sys.options_types.value" :type "text" :is_pk false :is_pk_in_new nil :label "Value" :control "text" :location 2 :in_table_view true :disabled false :readonly false :required true :text_max_length 25 :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:fields_id "sys.options_types.location" :type "int8" :is_pk false :is_pk_in_new nil :label "Location" :control "integer" :location 8 :in_table_view true :disabled false :readonly false :required true :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step 1 :integer_min 0 :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:fields_id "sys.options_usergroups.id" :type "serial8" :is_pk true :is_pk_in_new nil :label "ID" :control "integer-key" :location 0 :in_table_view true :disabled false :readonly true :required false :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:fields_id "sys.options_usergroups.label" :type "text" :is_pk false :is_pk_in_new nil :label "Label" :control "text" :location 1 :in_table_view true :disabled false :readonly false :required true :text_max_length 25 :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:fields_id "sys.options_usergroups.value" :type "text" :is_pk false :is_pk_in_new nil :label "Value" :control "text" :location 2 :in_table_view true :disabled false :readonly false :required true :text_max_length 25 :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:fields_id "sys.options_usergroups.location" :type "int8" :is_pk false :is_pk_in_new nil :label "Location" :control "integer" :location 8 :in_table_view true :disabled false :readonly false :required true :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step 1 :integer_min 0 :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:fields_id "sys.options_function_names.value" :type "text" :is_pk true :is_pk_in_new true :label "Value" :control "text-key" :location 0 :in_table_view true :disabled false :readonly true :required false :text_max_length 10 :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:fields_id "sys.options_function_names.label" :type "text" :is_pk false :is_pk_in_new nil :label "Label" :control "text" :location 1 :in_table_view true :disabled false :readonly false :required true :text_max_length 25 :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:fields_id "sys.options_function_names.location" :type "int8" :is_pk false :is_pk_in_new nil :label "Location" :control "integer" :location 2 :in_table_view true :disabled false :readonly false :required true :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step 1 :integer_min 0 :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:fields_id "sys.event_classes.event_classes_id" :type "text" :is_pk true :is_pk_in_new true :label "Event Classes ID" :control "text-key" :location 0 :in_table_view true :disabled false :readonly true :required false :text_max_length 10 :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:fields_id "sys.event_classes.function_name" :type "text" :is_pk false :is_pk_in_new nil :label "Function name" :control "text" :location 1 :in_table_view true :disabled false :readonly false :required true :text_max_length 25 :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:fields_id "sys.event_classes.argument_name_id" :type "int8" :is_pk false :is_pk_in_new nil :label "Argument Name ID" :control "foreign-key-static" :location 2 :in_table_view true :disabled false :readonly true :required false :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query "select-sys-fields-all" :foreign_key_size 5 :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:fields_id "sys.event_classes.description" :type "text" :is_pk false :is_pk_in_new nil :label "Description" :control "textarea" :location 3 :in_table_view true :disabled false :readonly false :required true :text_max_length 25 :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:fields_id "sys.event_classes_fields.event_classes_fields_id" :type "serial8" :is_pk true :is_pk_in_new nil :label "Event Classes Fields ID" :control "integer-key" :location 0 :in_table_view true :disabled false :readonly true :required false :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:fields_id "sys.event_classes_fields.event_classes_id" :type "int8" :is_pk false :is_pk_in_new nil :label "Event Classes ID" :control "foreign-key-static" :location 1 :in_table_view true :disabled false :readonly true :required false :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query "select-sys-event-classes-all" :foreign_key_size 5 :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:fields_id "sys.event_classes_fields.fields_id" :type "int8" :is_pk false :is_pk_in_new nil :label "Fields ID" :control "foreign-key-static" :location 2 :in_table_view true :disabled false :readonly true :required false :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query "select-sys-fields-all" :foreign_key_size 5 :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:fields_id "sys.event_classes_fields.location" :type "int8" :is_pk false :is_pk_in_new nil :label "Location" :control "integer" :location 3 :in_table_view true :disabled false :readonly false :required true :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step 1 :integer_min 0 :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:fields_id "sys.event_classes_fields.disabled" :type "boolean" :is_pk false :is_pk_in_new nil :label "Disabled?" :control "boolean-select" :location 24 :in_table_view false :disabled false :readonly false :required true :text_max_length nil :boolean_true "Yes" :boolean_false "No" :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:fields_id "sys.event_classes_fields.readonly" :type "boolean" :is_pk false :is_pk_in_new nil :label "Readonly?" :control "boolean-select" :location 25 :in_table_view false :disabled false :readonly false :required true :text_max_length nil :boolean_true "Yes" :boolean_false "No" :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:fields_id "sys.event_classes_fields.required" :type "boolean" :is_pk false :is_pk_in_new nil :label "Required?" :control "boolean-select" :location 26 :in_table_view false :disabled false :readonly false :required true :text_max_length nil :boolean_true "Yes" :boolean_false "No" :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

