{:schema_name "sys" :table_name "fields" :field_name "fields_id" :type "serial8" :is_pk true :is_pk_in_new nil :label "Fields ID" :control "integer-key" :location 0 :in_table_view true :disabled false :readonly true :required false :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "schema_name" :type "text" :is_pk false :is_pk_in_new nil :label "Schema Name" :control "text" :location 1 :in_table_view true :disabled false :readonly false :required true :text_max_length 25 :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "table_name" :type "text" :is_pk false :is_pk_in_new nil :label "Table Name" :control "text" :location 2 :in_table_view true :disabled false :readonly false :required true :text_max_length 25 :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "field_name" :type "text" :is_pk false :is_pk_in_new nil :label "Field Name" :control "text" :location 3 :in_table_view true :disabled false :readonly false :required true :text_max_length 25 :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "type" :type "text" :is_pk false :is_pk_in_new nil :label "Type" :control "select" :location 4 :in_table_view true :disabled false :readonly false :required true :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple false :select_size 1 :options_schema_table "sys.options_types" :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "is_pk" :type "boolean" :is_pk false :is_pk_in_new nil :label "Is Primary Key?" :control "boolean-select" :location 5 :in_table_view false :disabled false :readonly false :required true :text_max_length nil :boolean_true "Yes" :boolean_false "No" :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "is_pk_in_new" :type "boolean" :is_pk false :is_pk_in_new nil :label "Is Primary Key In New?" :control "boolean-select" :location 6 :in_table_view false :disabled false :readonly false :required true :text_max_length nil :boolean_true "Yes" :boolean_false "No" :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "label" :type "text" :is_pk false :is_pk_in_new nil :label "Label" :control "text" :location 7 :in_table_view true :disabled false :readonly false :required true :text_max_length 25 :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "control" :type "text" :is_pk false :is_pk_in_new nil :label "Control" :control "select" :location 8 :in_table_view true :disabled false :readonly false :required true :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple false :select_size 1 :options_schema_table "sys.options_controls" :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "location" :type "int8" :is_pk false :is_pk_in_new nil :label "Location" :control "integer" :location 9 :in_table_view false :disabled false :readonly false :required true :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step 1 :integer_min 0 :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "in_table_view" :type "boolean" :is_pk false :is_pk_in_new nil :label "In Table View?" :control "boolean-select" :location 10 :in_table_view false :disabled false :readonly false :required true :text_max_length nil :boolean_true "Yes" :boolean_false "No" :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "boolean_true" :type "text" :is_pk false :is_pk_in_new nil :label "Boolean True" :control "text" :location 11 :in_table_view false :disabled false :readonly false :required false :text_max_length 25 :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "boolean_false" :type "text" :is_pk false :is_pk_in_new nil :label "Boolean False" :control "text" :location 12 :in_table_view false :disabled false :readonly false :required false :text_max_length 25 :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "date_min" :type "date" :is_pk false :is_pk_in_new nil :label "Date Min" :control "date" :location 13 :in_table_view false :disabled false :readonly false :required false :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "date_max" :type "date" :is_pk false :is_pk_in_new nil :label "Date Max" :control "date" :location 14 :in_table_view false :disabled false :readonly false :required false :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "integer_step" :type "int8" :is_pk false :is_pk_in_new nil :label "Integer Step" :control "integer" :location 15 :in_table_view false :disabled false :readonly false :required false :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step 1 :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "integer_min" :type "int8" :is_pk false :is_pk_in_new nil :label "Integer Min" :control "integer" :location 16 :in_table_view false :disabled false :readonly false :required false :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step 1 :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "integer_max" :type "int8" :is_pk false :is_pk_in_new nil :label "Integer Max" :control "integer" :location 17 :in_table_view false :disabled false :readonly false :required false :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step 1 :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "float_step" :type "float8" :is_pk false :is_pk_in_new nil :label "Float Step" :control "float" :location 18 :in_table_view false :disabled false :readonly false :required false :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step 1.0E-10 :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "float_min" :type "float8" :is_pk false :is_pk_in_new nil :label "Float Min" :control "float" :location 19 :in_table_view false :disabled false :readonly false :required false :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step 1.0E-10 :float_min -1.0E-307 :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "float_max" :type "float8" :is_pk false :is_pk_in_new nil :label "Float Max" :control "float" :location 20 :in_table_view false :disabled false :readonly false :required false :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step 1.0E-10 :float_min nil :float_max 1.0E308 :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "select_multiple" :type "boolean" :is_pk false :is_pk_in_new nil :label "Select Multiple?" :control "boolean-select" :location 21 :in_table_view false :disabled false :readonly false :required false :text_max_length nil :boolean_true "Yes" :boolean_false "No" :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "select_size" :type "int8" :is_pk false :is_pk_in_new nil :label "Select Size" :control "integer" :location 22 :in_table_view false :disabled false :readonly false :required false :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step 1 :integer_min 0 :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "options_schema_table" :type "text" :is_pk false :is_pk_in_new nil :label "Options Schema Table" :control "text" :location 23 :in_table_view false :disabled false :readonly false :required false :text_max_length 24 :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "text_max_length" :type "int8" :is_pk false :is_pk_in_new nil :label "Text Max Length" :control "integer" :location 24 :in_table_view false :disabled false :readonly false :required false :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step 1 :integer_min 1 :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "disabled" :type "boolean" :is_pk false :is_pk_in_new nil :label "Disabled?" :control "boolean-select" :location 25 :in_table_view false :disabled false :readonly false :required true :text_max_length nil :boolean_true "Yes" :boolean_false "No" :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "readonly" :type "boolean" :is_pk false :is_pk_in_new nil :label "Readonly?" :control "boolean-select" :location 26 :in_table_view false :disabled false :readonly false :required true :text_max_length nil :boolean_true "Yes" :boolean_false "No" :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "fields" :field_name "required" :type "boolean" :is_pk false :is_pk_in_new nil :label "Required?" :control "boolean-select" :location 27 :in_table_view false :disabled false :readonly false :required true :text_max_length nil :boolean_true "Yes" :boolean_false "No" :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}


{:schema_name "sys" :table_name "users" :field_name "id" :type "uuid" :is_pk true :is_pk_in_new nil :label "ID" :control "text" :location 0 :in_table_view true :disabled false :readonly true :required false :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "users" :field_name "username" :type "text" :is_pk false :is_pk_in_new nil :label "Username" :control "text" :location 1 :in_table_view true :disabled false :readonly false :required true :text_max_length 25 :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "users" :field_name "password" :type "text" :is_pk false :is_pk_in_new nil :label "Password" :control "text" :location 2 :in_table_view true :disabled false :readonly false :required true :text_max_length 25 :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "users" :field_name "usergroup" :type "text" :is_pk false :is_pk_in_new nil :label "Usergroup" :control "select" :location 3 :in_table_view true :disabled false :readonly false :required true :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple false :select_size 1 :options_schema_table "sys.options_usergroups" :created_by "root" :updated_by "root"}


{:schema_name "sys" :table_name "options_controls" :field_name "id" :type "serial8" :is_pk true :is_pk_in_new nil :label "ID" :control "integer-key" :location 0 :in_table_view true :disabled false :readonly true :required false :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "options_controls" :field_name "label" :type "text" :is_pk false :is_pk_in_new nil :label "Label" :control "text" :location 1 :in_table_view true :disabled false :readonly false :required true :text_max_length 25 :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "options_controls" :field_name "value" :type "text" :is_pk false :is_pk_in_new nil :label "Value" :control "text" :location 2 :in_table_view true :disabled false :readonly false :required true :text_max_length 25 :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "options_controls" :field_name "location" :type "int8" :is_pk false :is_pk_in_new nil :label "Location" :control "integer" :location 8 :in_table_view true :disabled false :readonly false :required true :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step 1 :integer_min 0 :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}



{:schema_name "sys" :table_name "options_types" :field_name "id" :type "serial8" :is_pk true :is_pk_in_new nil :label "ID" :control "integer-key" :location 0 :in_table_view true :disabled false :readonly true :required false :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "options_types" :field_name "label" :type "text" :is_pk false :is_pk_in_new nil :label "Label" :control "text" :location 1 :in_table_view true :disabled false :readonly false :required true :text_max_length 25 :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "options_types" :field_name "value" :type "text" :is_pk false :is_pk_in_new nil :label "Value" :control "text" :location 2 :in_table_view true :disabled false :readonly false :required true :text_max_length 25 :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "options_types" :field_name "location" :type "int8" :is_pk false :is_pk_in_new nil :label "Location" :control "integer" :location 8 :in_table_view true :disabled false :readonly false :required true :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step 1 :integer_min 0 :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}



{:schema_name "sys" :table_name "options_usergroups" :field_name "id" :type "serial8" :is_pk true :is_pk_in_new nil :label "ID" :control "integer-key" :location 0 :in_table_view true :disabled false :readonly true :required false :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "options_usergroups" :field_name "label" :type "text" :is_pk false :is_pk_in_new nil :label "Label" :control "text" :location 1 :in_table_view true :disabled false :readonly false :required true :text_max_length 25 :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "options_usergroups" :field_name "value" :type "text" :is_pk false :is_pk_in_new nil :label "Value" :control "text" :location 2 :in_table_view true :disabled false :readonly false :required true :text_max_length 25 :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "options_usergroups" :field_name "location" :type "int8" :is_pk false :is_pk_in_new nil :label "Location" :control "integer" :location 8 :in_table_view true :disabled false :readonly false :required true :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step 1 :integer_min 0 :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}



{:schema_name "sys" :table_name "options_function_names" :field_name "value" :type "text" :is_pk true :is_pk_in_new true :label "Value" :control "text-key" :location 0 :in_table_view true :disabled false :readonly true :required false :text_max_length 10 :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "options_function_names" :field_name "label" :type "text" :is_pk false :is_pk_in_new nil :label "Label" :control "text" :location 1 :in_table_view true :disabled false :readonly false :required true :text_max_length 25 :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "options_function_names" :field_name "location" :type "int8" :is_pk false :is_pk_in_new nil :label "Location" :control "integer" :location 2 :in_table_view true :disabled false :readonly false :required true :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step 1 :integer_min 0 :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}



{:schema_name "sys" :table_name "event_classes" :field_name "event_classes_id" :type "text" :is_pk true :is_pk_in_new true :label "Event Classes ID" :control "text-key" :location 0 :in_table_view true :disabled false :readonly true :required false :text_max_length 10 :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "event_classes" :field_name "function_name" :type "text" :is_pk false :is_pk_in_new nil :label "Function name" :control "text" :location 1 :in_table_view true :disabled false :readonly false :required true :text_max_length 25 :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "event_classes" :field_name "argument_name_id" :type "int8" :is_pk false :is_pk_in_new nil :label "Argument Name ID" :control "foreign-key-static" :location 2 :in_table_view true :disabled false :readonly true :required false :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query "select-sys-fields-all" :foreign_key_size 5 :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "event_classes" :field_name "description" :type "text" :is_pk false :is_pk_in_new nil :label "Description" :control "textarea" :location 3 :in_table_view true :disabled false :readonly false :required true :text_max_length 25 :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}



{:schema_name "sys" :table_name "event_classes_fields" :field_name "event_classes_fields_id" :type "serial8" :is_pk true :is_pk_in_new nil :label "Event Classes Fields ID" :control "integer-key" :location 0 :in_table_view true :disabled false :readonly true :required false :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "event_classes_fields" :field_name "event_classes_id" :type "int8" :is_pk false :is_pk_in_new nil :label "Event Classes ID" :control "foreign-key-static" :location 1 :in_table_view true :disabled false :readonly true :required false :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query "select-sys-event-classes-all" :foreign_key_size 5 :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "event_classes_fields" :field_name "fields_id" :type "int8" :is_pk false :is_pk_in_new nil :label "Fields ID" :control "foreign-key-static" :location 2 :in_table_view true :disabled false :readonly true :required false :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query "select-sys-fields-all" :foreign_key_size 5 :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "event_classes_fields" :field_name "location" :type "int8" :is_pk false :is_pk_in_new nil :label "Location" :control "integer" :location 3 :in_table_view true :disabled false :readonly false :required true :text_max_length nil :boolean_true nil :boolean_false nil :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step 1 :integer_min 0 :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "event_classes_fields" :field_name "disabled" :type "boolean" :is_pk false :is_pk_in_new nil :label "Disabled?" :control "boolean-select" :location 24 :in_table_view false :disabled false :readonly false :required true :text_max_length nil :boolean_true "Yes" :boolean_false "No" :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "event_classes_fields" :field_name "readonly" :type "boolean" :is_pk false :is_pk_in_new nil :label "Readonly?" :control "boolean-select" :location 25 :in_table_view false :disabled false :readonly false :required true :text_max_length nil :boolean_true "Yes" :boolean_false "No" :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

{:schema_name "sys" :table_name "event_classes_fields" :field_name "required" :type "boolean" :is_pk false :is_pk_in_new nil :label "Required?" :control "boolean-select" :location 26 :in_table_view false :disabled false :readonly false :required true :text_max_length nil :boolean_true "Yes" :boolean_false "No" :date_min nil :date_max nil :foreign_key_query nil :foreign_key_size nil :integer_step nil :integer_min nil :integer_max nil :float_step nil :float_min nil :float_max nil :select_multiple nil :select_size nil :options_schema_table nil :created_by "root" :updated_by "root"}

